### PR TITLE
Nh/webpack optimization

### PR DESCRIPTION
**Pull request by nh758**
This is meant to optimize our app loading using webpack's available tools. Here are the significant changes:
1. Modifies our webpack config to hash files so that we can safely cache them, ensuring users get new code when its available (See: https://webpack.js.org/guides/caching/#root). Instead of generating a single app.js file, several smaller files are generated in the assets/app folder. This means when we change something we can still load unchanged files from cache.
2. Since Webpack generated files will now include a hash, to serve the correct scripts we need to update `index.html`. Webpack can do this for us, but to prevent `api_sails` and `web` services from getting out of sync, I changed `index.html` to a static file (generated by webpack), served by Nginx from the `web` service.
3. Also added a loading screen, so that user can see what's happening before the portal is loaded.
4. After logging in we used to reload the page. However, occasionally the session was getting reset (I think because we switch from Socket to REST requests, which sails should support). We don't actually need to reload the site, but can just call `bootstrap.init()` again.

To work it also requires changes in:
- runtime: https://github.com/digi-serve/ab_runtime/pull/30
- web service: https://github.com/digi-serve/ab_service_web/pull/1
- api sails service: https://github.com/digi-serve/ab_service_api_sails/pull/20

### CODE REVIEW

**Review by guyyoo — APPROVED** [review]
LGTM

**Comment by jamesduncan** [comment]
Lots going on here. I am hopeful these changes will help us speed up the load time as well as better communicate to the user that something is happening. We really need to figure out why the "conditional record rules - greater than 1" test is not passing. It seems to not just be this commit but others without these changes are failing as well.

**Comment by nh758** [comment]
> Lots going on here. I am hopeful these changes will help us speed up the load time as well as better communicate to the user that something is happening. We really need to figure out why the "conditional record rules - greater than 1" test is not passing. It seems to not just be this commit but others without these changes are failing as well.

Note the tests here don't actually test these changes. `index.html` is still served by sails, and references `app.js` which is still in the web service. Where this code generates files in a new folder `app` and expects nginx to serve the `index.html` generated by this code (requires change in the `nginx.conf` in runtime). Basically we need changes in multiple places to accurately test this. 

But yeah, I am seeing that test fail quite frequently and inconsistently. Even here it passed with the develop build of ab-web, but not master. We should probably skip it until we can stabilize it.

**Review by wongpratan — APPROVED** [review]
New loading is super nice.

**Review by jamesduncan — APPROVED** [review]

**Pull request merged**
