### PR TITLE
changes to get data results for docx closer to v1 specs

### PR DESCRIPTION
**Pull request by jamesduncan**

### CODE REVIEW

**Comment by jamesduncan** [comment]
This is only partial complete. I am having trouble getting the nested `data` to populate fully. I am considering just going back to the previous method...I am not totally sure why it was rewritten but it handled the recursive data population a little better.

**Review by wongpratan — APPROVED** [review]

**Review by wongpratan — APPROVED** [review]

**Review by wongpratan — APPROVED** [review]

**Comment by jamesduncan** [comment]
@wongpratan do you know enough about this to try to figure out the nested data population? I cannot seem to figure it out?

**Comment by wongpratan** [comment]
@jamesduncan 
https://github.com/digi-serve/ab_platform_web/blob/master/AppBuilder/platform/views/viewComponent/ABViewDocxBuilderComponent.js#L267
```
resultData = Object.assign(
    resultData ?? {},
    this.setReportValues(data, f, fieldLabels, mlFields) ?? {}
);
```
I updated code at this and add `Admission info` data. It works for me.

**Comment by jamesduncan** [comment]
Closing this PR and opening a new one with Pong's fix.

**Pull request closed without merging**
